# Generated by Django 4.1 on 2022-08-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airxiapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("name", "email", "subject")},
        ),
    ]
