# Generated by Django 4.1 on 2022-08-23 14:14

import airxiapp.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airxiapp", "0002_alter_contact_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="reference_number",
            field=models.CharField(
                default=airxiapp.helpers.reference_number_generator,
                editable=False,
                max_length=20,
            ),
        ),
    ]
