# Generated by Django 4.1 on 2022-08-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airxiapp", "0003_alter_booking_reference_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="reference_number",
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
