# Generated by Django 4.1 on 2022-08-23 23:43

import airxiapp.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airxiapp", "0004_alter_booking_reference_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxi",
            name="Type",
            field=models.CharField(
                choices=[
                    ("SUV", "SUV"),
                    ("Limousine", "Limousine"),
                    ("Hybrid", "Hybrid"),
                    ("Cab", "Cab"),
                ],
                max_length=225,
            ),
        ),
        migrations.AlterField(
            model_name="taxi",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=airxiapp.helpers.get_media_paths
            ),
        ),
    ]
