# Generated by Django 4.1 on 2022-09-01 11:24

import airxiapp.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("airxiapp", "0005_alter_taxi_type_alter_taxi_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="taxi",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="taxi",
                to="airxiapp.taxi",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="reference_number",
            field=models.CharField(
                default=airxiapp.helpers.reference_number_generator,
                editable=False,
                max_length=20,
            ),
        ),
    ]
