# Generated by Django 4.1 on 2022-09-08 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("airxiapp", "0007_alter_contact_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="taxi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="bookings",
                to="airxiapp.taxi",
            ),
        ),
    ]
