# Generated by Django 4.1 on 2022-09-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_managers_remove_user_username_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="-", max_length=255),
            preserve_default=False,
        ),
    ]
